from django.urls import path
from . import views
from .views import Base, AView, BView, CView, DView, EView, FView, GView, HView, IView, JView, KView, LView, MView, NView, OView, PView, QView, RView, SView, TView, UView, VView, WView, XView, YView, ZView, ÆView, ØView, ÅView#, Tilføj#, GætView, Info, 

urlpatterns = [
    path('', Base.as_view(), name='info'),
    path('danska/', AView.as_view(), name='danska'),
    path('danskb/', BView.as_view(), name='danskb'),
    path('danskc/', CView.as_view(), name='danskc'),
    path('danskd/', DView.as_view(), name='danskd'),
    path('danske/', EView.as_view(), name='danske'),
    path('danskf/', FView.as_view(), name='danskf'),
    path('danskg/', GView.as_view(), name='danskg'),
    path('danskh/', HView.as_view(), name='danskh'),
    path('danski/', IView.as_view(), name='danski'),
    path('danskj/', JView.as_view(), name='danskj'),
    path('danskk/', KView.as_view(), name='danskk'),
    path('danskl/', LView.as_view(), name='danskl'),
    path('danskm/', MView.as_view(), name='danskm'),
    path('danskn/', NView.as_view(), name='danskn'),
    path('dansko/', OView.as_view(), name='dansko'),
    path('danskp/', PView.as_view(), name='danskp'),
    path('danskq/', QView.as_view(), name='danskq'),
    path('danskr/', RView.as_view(), name='danskr'),
    path('dansks/', SView.as_view(), name='dansks'),
    path('danskt/', TView.as_view(), name='danskt'),
    path('dansku/', UView.as_view(), name='dansku'),
    path('danskv/', VView.as_view(), name='danskv'),
    path('danskw/', WView.as_view(), name='danskw'),
    path('danskx/', XView.as_view(), name='danskx'),
    path('dansky/', YView.as_view(), name='dansky'),
    path('danskz/', ZView.as_view(), name='danskz'),
    path('danskæ/', ÆView.as_view(), name='danskæ'),
    path('danskø/', ØView.as_view(), name='danskø'),
    path('danskå/', ÅView.as_view(), name='danskå'),
    #path('tilføj/', Tilføj.as_view(), name='tilføj'),
]