# Generated by Django 5.0.14 on 2026-01-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bogstav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogstav', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alfabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('danord', models.CharField(blank=True, max_length=50)),
                ('tysord', models.CharField(blank=True, max_length=50)),
                ('engord', models.CharField(blank=True, max_length=50)),
                ('danbe', models.TextField(blank=True)),
                ('tysbe', models.TextField(blank=True)),
                ('engbe', models.TextField(blank=True)),
                ('bogstav', models.ManyToManyField(related_name='item', to='dansk.bogstav')),
            ],
        ),
    ]
